### ISSUE TITLE
EchoDemo does not working

### ISSUE THREAD

**Issue by xlebeling** [Margaruga/JavaWhatsApp#3]
hey everyone,

i can't get the EchoDemo running. 
If i run  sudo java com.nqysit.whatsapp.EchoDemo, I get the following:

`Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/JsonParser
        at com.nqysit.whatsapp.Client.parseMessages(Client.java:128)
        at com.nqysit.whatsapp.Client.ListenIncomingMessages(Client.java:58)
        at com.nqysit.whatsapp.EchoDemo.main(EchoDemo.java:28)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonParser
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
`
Does anybody got an idea?

**Comment by regonza** [comment]
I have the same issue. :(

**Comment by yaolau** [comment]
lost a gson jar, but i add the jar, it still not work.

**Comment by brunodeandrade** [comment]
Someone has solved this issue????

**Comment by DavidePastore** [comment]
Don't forget to launch:

    mvn clean install

in Whatsapp directory.

**Comment by ChanakaDil** [comment]
It is not a Maven directory to run mvn clean install

**Comment by viveksachdeva** [comment]
I am also not able to run but its due to exception "Stream Closed" in method pipe of class Client:
```
       Exception in thread "main" java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at de.robertduda.whatsapp.Client.parseMessages(Client.java:114)
	at de.robertduda.whatsapp.Client.listenIncomingMessages(Client.java:45)
	at de.robertduda.whatsapp.EchoDemo.main(EchoDemo.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
